ID: 2026Y-05M-07D-12h00m00s_N1Dx
PID: 318434
START_DATETIME: 2026-05-07 12:00:00.325284
FILE: /home/ywatanabe/proj/scitex-app/examples/01_basic_file_operations.py
SDIR_OUT: /home/ywatanabe/proj/scitex-app/examples/01_basic_file_operations_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-app/examples/01_basic_file_operations_out/RUNNING/2026Y-05M-07D-12h00m00s_N1Dx-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-05-07 12:00:05.406022
RUN_DURATION: 00:00:05
