"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil
from pathlib import Path

import pytest


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # PIN THE TREE. Without `path=`, audit-all resolves its own target by
    # GUESSING FROM CWD — so running pytest from the main checkout while
    # editing a linked worktree grades the WRONG TREE and still reports a
    # confident pass. Measured 2026-09-06: a violation that CI caught
    # (STX-TQ002, PR #158) passed here three times, because cwd was the main
    # checkout on develop and the edit was in .worktrees/. scitex-dev warns
    # about this on stderr; a warning nobody reads is not a guard.
    repo_root = Path(__file__).resolve().parents[2]
    audit_all_for_package('scitex-app', path=repo_root)
