"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-app",
        skip_rules=(
            "PS-121",  # _sphinx_html bundle — populated by docs.yml CI
            # 6/6 Python APIs unmapped to MCP tools, and 9 MCP tools have
            # no Python API. Real architectural-parity gap; per-API decision
            # needed (file-system tools may stay MCP-only by design).
            "§6",
        ),
    )
